### ISSUE TITLE
Don't import implementation files from another package in generated plugin registrant.

### ISSUE THREAD

**Issue by thoward27** [PostHog/posthog-flutter#12]
With the most recent version of posthog-flutter, running on the latest stable version of flutter (2.2.2), I am seeing an issue in `flutter analyze` for the `generated_plugin_registrant.dart` file.

It seems that flutter does not like the fact that it has to import `PosthogWeb` from your `src` directory. 

Other people have had similar issues elsewhere:
- https://github.com/Baseflow/flutter-geolocator/issues/582
- https://github.com/aissat/easy_localization/issues/159

**Comment by shinyo17** [comment]
I have error in Flutter Web too.
https://posthogusers.slack.com/archives/CT7HXDEG3/p1623146653167600

**Comment by yakkomajuri** [comment]
Thanks for reporting this - I'll look into it

**Comment by yakkomajuri** [comment]
I'll release a new version today and would appreciate if you could test it out and see if #13 truly fixed it!

**Comment by yakkomajuri** [comment]
(for context, this was just a matter of updating our example, not the code)

**Comment by yakkomajuri** [comment]
Alright so this was just a problem in an example file that shouldn't have been committed anyway. I've removed that file from the lib. Pretty annoying the flutter automatically generates a file with a warning though.

Hope everything else is working? I'm doing some testing on the web side now.

**Comment by thoward27** [comment]
On latest posthog flutter I'm still seeing errors from `flutter analyze`. 

When flutter builds the `generated_plugin_registrant.dart` file with `posthog` installed, it produces 

```
//
// Generated file. Do not edit.
//

// ignore_for_file: lines_longer_than_80_chars

import 'package:audioplayers/web/audioplayers_web.dart';
import 'package:fluttertoast/fluttertoast_web.dart';
import 'package:libphonenumber_web/libphonenumber_web.dart';
import 'package:posthog_flutter/src/posthog_web.dart';
import 'package:shared_preferences_web/shared_preferences_web.dart';
import 'package:url_launcher_web/url_launcher_web.dart';
import 'package:video_player_web/video_player_web.dart';
import 'package:wakelock_web/wakelock_web.dart';

import 'package:flutter_web_plugins/flutter_web_plugins.dart';

// ignore: public_member_api_docs
void registerPlugins(Registrar registrar) {
  AudioplayersPlugin.registerWith(registrar);
  FluttertoastWebPlugin.registerWith(registrar);
  LibPhoneNumberPlugin.registerWith(registrar);
  PosthogWeb.registerWith(registrar);
  SharedPreferencesPlugin.registerWith(registrar);
  UrlLauncherPlugin.registerWith(registrar);
  VideoPlayerPlugin.registerWith(registrar);
  WakelockWeb.registerWith(registrar);
  registrar.registerMessageHandler();
}
```

Flutter analyze then complains

```
❯ flutter analyze
Analyzing aa_refresher...                                               

   info • Don't import implementation files from another package • lib/generated_plugin_registrant.dart:10:8 • implementation_imports

1 issue found. (ran in 2.0s)
```

It is complaining about the fact that it has to import `posthog_web` from your `src` directory.
