### ISSUE TITLE
[iOS] Swift Compiler Error: Missing helper functions in PosthogFlutterPlugin.swift

### ISSUE THREAD

**Issue by lukeyuen701** [PostHog/posthog-flutter#125]
### Version

4.7.0

### Steps to Reproduce

Swift Compiler Errors in PosthogFlutterPlugin.swift:
1. Line 182: Cannot find 'dateToMillis' in scope
2. Line 217: Cannot find 'dateToMillis' in scope
3. Line 235: Cannot find 'imageToBase64' in scope

### Expected Result

Application should build successfully.

### Actual Result

Build fails with Swift compiler errors due to missing helper functions.

**Comment by marandaneto** [comment]
@lukeyuen701 https://posthog.com/docs/session-replay/installation?tab=Flutter#troubleshooting
you need to upgrade your cocoa pods to the latest version.

**Comment by lukeyuen701** [comment]
@marandaneto Build still fails with Pod v1.16.2. Rolling back to v4.6.0 works.

**Comment by marandaneto** [comment]
@lukeyuen701 what do you mean by Pod v1.16.2? the PostHog iOS pod should be >= 3.6.1 https://github.com/PostHog/posthog-ios/blob/main/CHANGELOG.md#3161---2024-12-04

**Comment by marandaneto** [comment]
Clean your pods and reinstall if needed, also update your Pods repo.

**Comment by lukeyuen701** [comment]
@marandaneto 

Copy
I apologize if I wasn't clear enough earlier. Let me provide more details about the issue:

Environment:
- CocoaPods version: 1.16.2
- PostHog Flutter version: 4.7.0 

When running Flutter on iOS, I'm getting the following Swift compiler errors:

1. Swift Compiler Error (Xcode): Cannot find 'dateToMillis' in scope
File: PosthogFlutterPlugin.swift:182:28

2. Swift Compiler Error (Xcode): Cannot find 'dateToMillis' in scope
File: PosthogFlutterPlugin.swift:217:28

3. Swift Compiler Error (Xcode): Cannot find 'imageToBase64' in scope
File: PosthogFlutterPlugin.swift:235:39

Path to error files:
/.pub-cache/hosted/pub.dev/posthog_flutter-4.7.0/ios/Classes/PosthogFlutterPlugin.swift

**Comment by marandaneto** [comment]
@lukeyuen701 you have to upgrade your cocoapods, not the cocoapods tool but the [cocoapods dependencies](https://guides.cocoapods.org/using/pod-install-vs-update.html)

check the `ios` folder, check the `ios/Podfile.lock` file etc.

**Comment by lukeyuen701** [comment]
> @lukeyuen701 you have to upgrade your cocoapods, not the cocoapods tool but the [cocoapods dependencies](https://guides.cocoapods.org/using/pod-install-vs-update.html)
> 
> check the `ios` folder, check the `ios/Podfile.lock` file etc.

Thanks for walking me through this. It's all working now.
