### ISSUE TITLE
No config set from dart

### ISSUE THREAD

**Issue by alexsunderlion** [PostHog/posthog-flutter#22]
I haven't seen any method to set configuration(API_KEY, POSTHOG_HOST, TRACK_APPLICATION_LIFECYCLE_EVENTS, DEBUG) from dart layer.
Better to have `config/init` function to set API_KEY and other option based on dynamic environment from flutter.

**Comment by metafounder** [comment]
Up on this issue. Just to be clear: currently, the only way to set configuration is to hardcode them in info.plist for iOS?

**Comment by alexsunderlion** [comment]
Yes, we are only able to hardcode them in `info.plist`

**Comment by danielmeza** [comment]
I agree with this, I'm using FlutterFlow and there is now an easy way to edit platform specific code there, an init function is needed for such scenarios.

**Comment by marandaneto** [comment]
No updates, sorry, but we will consider it for the next major version.

**Comment by Maxim-Filimonov** [comment]
+1 would be great to have it as all other libs provide ability to pass tokens via init. 
We have different tokens for different envs and also would like to avoid hardcoding things in Info.plist

**Comment by flodaniel** [comment]
Adding that this is necessary to enable tracking of lifecycle events while staying compliant with cookie laws in the European Union.

**Comment by marandaneto** [comment]
> Adding that this is necessary to enable tracking of lifecycle events while staying compliant with cookie laws in the European Union.

It's possible to disable already so it's already compliant, only needed if you want to enable it again at runtime.

**Comment by marandaneto** [comment]
On Android, you could have a Manifest per flavor, see [comment](https://github.com/PostHog/posthog-flutter/issues/100#issuecomment-2076659431).
On iOS, you could use eg `PlistBuddy`, see [comment](https://github.com/PostHog/posthog-flutter/issues/100#issuecomment-2095532911).

**Comment by marandaneto** [comment]
[PR](https://github.com/PostHog/posthog-flutter/pull/117) is up
