### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by alexprice12** [PostHog/posthog-flutter#24]
On Android when I run this I get the following error:

```
E/flutter (21336): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method identify on channel posthogflutter)
E/flutter (21336): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
E/flutter (21336): <asynchronous suspension>
E/flutter (21336): #1      PosthogMethodChannel.identify (package:posthog_flutter/src/posthog_method_channel.dart:14:7)
E/flutter (21336): <asynchronous suspension>
```

I've followed the the instructions [here](https://pub.dev/packages/posthog_flutter). I also tried to run `flutter clean` with no luck.

**Comment by alexprice12** [comment]
It looks like this occurs only with hot reload and works OK for initial load or hot restart.

**Comment by marandaneto** [comment]
@alexprice12 does this happen on Android, iOS or Web?

**Comment by marandaneto** [comment]
@alexprice12 any feedback?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by justincbeck** [comment]
This just happened to me when running unit tests. I'm testing a method that calls `Posthog().identify()` and I'm getting this exception when the test runs. I can get around it by moving it out into a provider and then mocking that provider but that's not great. Happy to provide more info if that's helpful.

**Comment by marandaneto** [comment]
@justincbeck could it be that you did not call `TestWidgetsFlutterBinding.ensureInitialized();` in your tests?
Please open a new issue if needed with more context, flutter version, SDK version, the test itself, the stack trace, thanks.
