### ISSUE TITLE
Support Groups

### ISSUE THREAD

**Issue by fdaugs** [PostHog/posthog-flutter#26]
Currently the flutter plugin does the support the .group() call. 

At least for the native iOS and Web plugins this is available. So it should be possible to expose this through this plugin.

**Comment by purbojati** [comment]
+1 I have been eagerly awaiting the release of the Flutter SDK for Group Analytics.

**Comment by purbojati** [comment]
Hey PostHog Team, any update on Group Analytics support for Flutter? 
Thanks!

**Comment by purbojati** [comment]
Thanks a lot!
