### ISSUE TITLE
iOS build fails with ARC Semantic Issue (Xcode) on Version 3.0.4

### ISSUE THREAD

**Issue by Wizzel1** [PostHog/posthog-flutter#31]
I have just updated posthog for my iOS App but when building the App  I am getting an error:

```
Failed to build iOS app
Could not build the precompiled application for the device.
ARC Semantic Issue (Xcode): No visible @interface for 'PosthogFlutterPlugin' declares the selector 'reloadFeatureFlags:result:'
```

**Comment by dio-ralali** [comment]
have you found any solutions? I facing the same issue on my project.

<img width="1072" alt="CleanShot 2023-04-05 at 14 28 55@2x" src="https://user-images.githubusercontent.com/86591816/230011588-f9fd9995-e267-4b44-bbfd-ba2c3e9e624a.png">

**Comment by Wizzel1** [comment]
@dio-ralali No I haven't, I have downgraded the package back to 2.0.3 for now

**Comment by dio-ralali** [comment]
@Wizzel1 thanks. downgrading the package works for me too.
