### ISSUE TITLE
Question : Where to add screen method , in stateful widget

### ISSUE THREAD

**Issue by mazen930** [PostHog/posthog-flutter#32]
Posthog.screen(screenName: 'Example Screen',); , this method is added in build in stateless , but in stateful doesn't it make sense to be add in init not the build 
If so may be you need to update the example

**Comment by coder-Aayush** [comment]
@mazen930 you can add it in initState as well as addPostFrameCallback

```dart
WidgetsBinding.instance!.addPostFrameCallback((_) {
  // executes after build
})
```
