### ISSUE TITLE
ARC Semantic Issue (Xcode): No visible @interface for 'PosthogFlutterPlugin' declares the selector 'reloadFeatureFlags:result:'

### ISSUE THREAD

**Issue by coder-Aayush** [PostHog/posthog-flutter#33]
I have followed getting started guide and added configuration code for iOS. But facing issue while compiling.
Flutter version: 3.7.5 

posthog_flutter: 3.0.4

<details>
  <summary>Configuration</summary>

```plist

<key>com.posthog.posthog.API_KEY</key>
	<string>****</string>
	<key>com.posthog.posthog.POSTHOG_HOST</key>
	<string>https://app.posthog.com</string>
	<key>com.posthog.posthog.TRACK_APPLICATION_LIFECYCLE_EVENTS</key>
	<false/>

```
</details>

<details>
  <summary>Flutter Doctor</summary>

```dart
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.1 22C65 darwin-arm64, locale en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.76.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```
</details>

<details>
  <summary>Error Log</summary>

```dart
Launching lib/main_development.dart on iPhone 14 in debug mode...
main_development.dart:1
Xcode build done.                                            6.0s
Failed to build iOS app
ARC Semantic Issue (Xcode): No visible @interface for 'PosthogFlutterPlugin' declares the selector 'reloadFeatureFlags:result:'
/Users/.pub-cache/hosted/pub.dev/posthog_flutter-3.0.4/ios/Classes/PosthogFlutterPlugin.m:119:10

Could not build the application for the simulator.
Error launching application on iPhone 14.
Exited
```
</details>

**Comment by ajsharp** [comment]
Seeing same thing here.

**Comment by ajsharp** [comment]
From posthog [community support](https://posthogusers.slack.com/archives/C01GLBKHKQT/p1679609870172029?thread_ts=1678805719.691969&cid=C01GLBKHKQT):

> hi there! please roll back to pre 3.0.0 since that includes the breaking changes for feature flags.

**Comment by dio-ralali** [comment]
Facing the same issue here. 

`flutter doctor -v` result : 

<img width="1056" alt="CleanShot 2023-04-05 at 13 47 33@2x" src="https://user-images.githubusercontent.com/86591816/230002479-f071563b-3a16-4042-904b-aea4495b6a5f.png">

**Comment by FantaMagier** [comment]
I need the feature flag functions so please fix the error.
Thank You!

**Comment by dio-ralali** [comment]
Any updates on this issue? I really need the feature flag functions in my Flutter App.

**Comment by mgesmundo** [comment]
+1

**Comment by harshmittal2810** [comment]
@fuziontech Anyone from your team, can please check this ?
We have been waiting for this from long time.

**Comment by benjackwhite** [comment]
Sorry for the delay here. Looks like I can see where the issue might be and will prioritise getting a fix out
