### ISSUE TITLE
getFeatureFlagPayload support?

### ISSUE THREAD

**Issue by YourAverageTechBro** [PostHog/posthog-flutter#38]
Are there any plans to support the `getFeatureFlagPayload` function in this library? Or is there any workaround to get the payload for a feature flag?

**Comment by marandaneto** [comment]
@YourAverageTechBro indeed, still missing, would you like to make a PR and expose this method?
Also see [this](https://github.com/PostHog/posthog-flutter/issues/46) which is very similar.
