### ISSUE TITLE
email over-ridding 

### ISSUE THREAD

**Issue by johnson1940** [PostHog/posthog-flutter#44]
The email is overridden with the logged in user. I have tried with various devices still the same issue. And to resolve the issue I have   tried using the reset event at the logout event still facing the same issue any solution for that? for flutter application

**Comment by marandaneto** [comment]
@johnson1940 not sure I understood your question.
You called `posthog.identify` with an email, called `posthog.reset` but you still see the same email?

**Comment by marandaneto** [comment]
@johnson1940 any feedback?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
