### ISSUE TITLE
Why Experiment for AB Testing is not possible in flutter 

### ISSUE THREAD

**Issue by venkatp4** [PostHog/posthog-flutter#46]
Why Experiment for AB Testing is not possible in flutter

**Comment by marandaneto** [comment]
You can try this https://posthog.com/docs/experiments/running-experiments-without-feature-flags
But indeed, to run [experiments via feature flags](https://posthog.com/docs/libraries/js#experiments-ab-tests), we will need to export the `getFeatureFlag` method as well.
Would you like to submit a PR?
