### ISSUE TITLE
How to implement Groups Analytics with Flutter?

### ISSUE THREAD

**Issue by purbojati** [PostHog/posthog-flutter#47]
There is no Flutter guideline in Posthog documentation.

**Comment by marandaneto** [comment]
@purbojati only [docs](https://posthog.com/docs/product-analytics/group-analytics#the-difference-between-groups-and-cohorts) (code snippets) are missing apparently, but it's very similar to the other SDKs, you can check the source code [here](https://github.com/PostHog/posthog-flutter/blob/ede5e091855491a862c70953581171acfdc31ea1/lib/src/posthog.dart#L110).

**Comment by ahmadadzan** [comment]
I was trying this all day long and the groups still not coming into Groups Tab. What's wrong? Please help. Thanks!

sendEnvent(String eventName, [Map<String, dynamic>? properties]) {
    properties ??= {};
    properties['platform'] = Platform.isAndroid ? "android" : "ios";
    Posthog().group(
        groupType: 'Bisnis',
        groupKey: global.bussinessId,
        groupProperties: {'nama': 'cobacoba'});
    Posthog().capture(eventName: eventName, properties: properties);
  }

**Comment by marandaneto** [comment]
@ahmadadzan Can you check if your SDK init. is correct? docs is [here](https://posthog.com/docs/libraries/flutter).

Try to enable the `Posthog().debug(true)` flag and copy-paste the logs, so we can check what's going on.

Are you testing on Android or iOS?

**Comment by marandaneto** [comment]
@purbojati any feedback?

**Comment by purbojati** [comment]
@marandaneto No, unfortunately :( 
We are still using Posthog for event tracking, just that not Group analytics.

**Comment by marandaneto** [comment]
Ok, since I mentioned this is already [possible](https://github.com/PostHog/posthog-flutter/issues/47#issuecomment-1714331291), let me know if you find any issues.
