### ISSUE TITLE
Add session id to events so that they can be used in session duration analysis

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog-flutter#50]
Because there are no session ids on events they cannot be used for session duration analysis.

The current session duration analysis only cares that an event exists, has a timestamp, and has a `$session_id` property

**Comment by marandaneto** [comment]
Similar to https://github.com/PostHog/posthog-android/issues/28

**Comment by stephan1994w** [comment]
Any update on this issue?

**Comment by marandaneto** [comment]
Not yet, it depends on https://github.com/PostHog/posthog-flutter/pull/60 which adds the PH Android SDK v3, but the session_id is still missing on iOS, coming next.
