### ISSUE TITLE
Automatic lifecycle events don't work

### ISSUE THREAD

**Issue by rohan-mehta** [PostHog/posthog-flutter#63]
### Version

3.3.0

### Steps to Reproduce

Set this in the iOS Info.plist:
```
<key>com.posthog.posthog.TRACK_APPLICATION_LIFECYCLE_EVENTS</key>
<true/>
```

Then launch the app.

### Expected Result

App lifecycle events should be logged - e.g. app open

### Actual Result

No lifecycle events logged. Other events (e.g. identify, screen, captured events) work fine.

**Comment by marandaneto** [comment]
@rohan-mehta thanks for reporting this.
For some reason, the key is `com.posthog.posthog.CAPTURE_APPLICATION_LIFECYCLE_EVENTS` for iOS, I've fixed the readme file and example.
