### ISSUE TITLE
Add option to set user properties when capturing events

### ISSUE THREAD

**Issue by bakua** [PostHog/posthog-flutter#65]
### Problem Statement

The documentation for android sdk says this is possible. However this feature is omitted in Flutter sdk for some reason.

Can we add it please?

Btw it would be nice to be able to add user props without need to identify or send event. Same as Amplitude does.

Thanks

**Comment by marandaneto** [comment]
@bakua When you call eg `capture`, you can pass the `$set` or `$set_once` property to `properties`
There's an example [here](https://posthog.com/docs/libraries/flutter)

**Comment by bakua** [comment]
Thank you. I am assuming the `$` should be escaped, correct?

Like this

```dart
         Posthog.capture(
                eventName: 'button_clicked',
                properties: {
                  'foo': 'bar',
                  'number': 1337,
                  'clicked': true,
                  '\$set': {
                    'userProp': 'value1',
                    '\$groups': {
                      'company': 'twitter',
                    },
                  },
                  '\$set_once': {
                    'userProp': 'value2'
                  }
                },
              );
```
