### ISSUE TITLE
Posthog().disable() is not working for iOS.

### ISSUE THREAD

**Issue by TaranenkoDenis** [PostHog/posthog-flutter#91]
### Version

4.1.0

### Steps to Reproduce

1. `flutter pub add posthog_flutter`
2. Call `Posthog().disable()` after app starts on iOS simulator or device.
3. Send some events to the Posthog.

### Expected Result

Posthog doesn't send events after disabling.

### Actual Result

All events, including autocaptured, are shown in the Activity area after disabling.

**Comment by marandaneto** [comment]
@TaranenkoDenis I can confirm that, on it.
