### ISSUE TITLE
add privacy manifest for apple 

### ISSUE THREAD

**Issue by omarhadek** [PostHog/posthog-flutter#93]
### Problem Statement

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by marandaneto** [comment]
The iOS SDK underneath already has it https://github.com/PostHog/posthog-ios/blob/main/PostHog/Resources/PrivacyInfo.xcprivacy and I'm not sure if this one needs the PrivacyInfo as well since it'd be pretty much the same file but I guess it won't hurt anyway.
