### ISSUE TITLE
Gradle build failing due to missing PostHogConfig.defaultHost

### ISSUE THREAD

**Issue by dancamdev** [PostHog/posthog-flutter#96]
### Version

4.4.0

### Steps to Reproduce

1. Open the example
2. Run `flutter build apk`

### Expected Result

Builds flawlessly

### Actual Result

e: file:///Users/danielecambi/.pub-cache/hosted/pub.dev/posthog_flutter-4.0.0/android/src/main/kotlin/com/posthog/posthog_flutter/PosthogFlutterPlugin.kt:44:91 Unresolved reference: defaultHost

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':posthog_flutter:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by marandaneto** [comment]
Ups sorry, this field was renamed due to linting conventions, on it.

**Comment by PeteClubSeven** [comment]
Hey, it doesn't seem to have worked for me @marandaneto 

```
e: file:///Users/peterc/.pub-cache/hosted/pub.dev/posthog_flutter-4.4.1/android/src/main/kotlin/com/posthog/posthog_flutter/PosthogFlutterPlugin.kt:44:91 Unresolved reference: DEFAULT_HOST

FAILURE: Build failed with an exception.
```

**Comment by marandaneto** [comment]
@PeteClubSeven maybe some gradle caching on your side?

> ✓  Built build/app/outputs/flutter-apk/app-release.apk (18.1MB)

**Comment by PeteClubSeven** [comment]
> @PeteClubSeven maybe some gradle caching on your side?
> 
> > ✓  Built build/app/outputs/flutter-apk/app-release.apk (18.1MB)

Seems so. I ran flutter clean, flutter pub get, deleted the android/.gradle folder and my pub-cache. Nothing worked but I never deleted my $HOME/.gradle folder. Either way its working now with 4.4.1.
